version: '3.1'

services:
  backend:
    container_name: django_backend
    build: 
      context: ./
    ports: 
     - 8002:8000
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
    - "5433:5432"